export interface EnvSecrets {
  [key: string]: string;
}

const KEY_LINE = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/;
const HEADER = [
  '# DBDock Secrets - DO NOT COMMIT THIS FILE',
  '# Generated by dbdock init',
];
const APPEND_HEADER = [
  '# DBDock Secrets - DO NOT COMMIT THIS FILE',
  '# Added by dbdock init',
];

export function mergeEnvContent(
  original: string | null,
  secrets: EnvSecrets,
): string {
  const entries = Object.entries(secrets);

  if (original === null || original.trim() === '') {
    return [...HEADER, '', ...entries.map(([k, v]) => `${k}=${v}`), ''].join(
      '\n',
    );
  }

  const lines = original.split('\n');
  const remaining = new Map(entries);

  for (let i = 0; i < lines.length; i++) {
    const match = KEY_LINE.exec(lines[i]);
    if (match && remaining.has(match[1])) {
      lines[i] = `${match[1]}=${remaining.get(match[1])}`;
      remaining.delete(match[1]);
    }
  }

  if (remaining.size > 0) {
    if (lines.length > 0 && lines[lines.length - 1].trim() !== '') {
      lines.push('');
    }
    lines.push(...APPEND_HEADER);
    for (const [key, value] of remaining) {
      lines.push(`${key}=${value}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
