export class PostgresConfigHelper {
  static getArchiveCommandScript(archivePath: string): string {
    return `
#!/bin/bash
# PostgreSQL WAL Archive Command Script
# Generated by DBDock

WAL_FILE="$1"
WAL_PATH="$2"
ARCHIVE_PATH="${archivePath}"

# Create archive directory if it doesn't exist
mkdir -p "$ARCHIVE_PATH"

# Copy WAL file to archive location
cp "$WAL_PATH" "$ARCHIVE_PATH/$WAL_FILE"

# Signal DBDock to process this WAL file
# You can integrate this with DBDock's WAL archiver
# For now, we just copy it to the archive location

exit 0
`.trim();
  }

  static getPostgresqlConfSettings(archivePath: string): string {
    return `
# PostgreSQL Configuration for DBDock WAL Archiving
# Add these settings to postgresql.conf

# Enable WAL archiving
wal_level = replica
archive_mode = on
archive_command = 'test ! -f ${archivePath}/%f && cp %p ${archivePath}/%f'

# Archive timeout (optional - archives WAL every 5 minutes even if not full)
archive_timeout = 300

# WAL segment size (default is 16MB)
# Note: This is a compile-time setting and cannot be changed in postgresql.conf

# For better PITR recovery
full_page_writes = on
`.trim();
  }

  static getSetupInstructions(): string {
    return `
# DBDock WAL Archiving Setup Instructions

## 1. Configure PostgreSQL

Add the following to your postgresql.conf:

\`\`\`
wal_level = replica
archive_mode = on
archive_command = 'test ! -f /path/to/archive/%f && cp %p /path/to/archive/%f'
archive_timeout = 300
\`\`\`

## 2. Create Archive Directory

\`\`\`bash
mkdir -p /path/to/archive
chown postgres:postgres /path/to/archive
chmod 700 /path/to/archive
\`\`\`

## 3. Restart PostgreSQL

\`\`\`bash
sudo systemctl restart postgresql
\`\`\`

## 4. Verify Configuration

\`\`\`sql
SELECT name, setting FROM pg_settings WHERE name IN ('wal_level', 'archive_mode', 'archive_command');
\`\`\`

## 5. Monitor WAL Archiving

\`\`\`sql
SELECT * FROM pg_stat_archiver;
\`\`\`

## 6. Configure DBDock

Enable PITR in your dbdock.config.json:

\`\`\`json
{
  "pitr": {
    "enabled": true,
    "walIntervalSeconds": 300,
    "retentionDays": 30
  }
}
\`\`\`

## 7. Archive WAL Files with DBDock

You can manually archive WAL files or set up a cron job:

\`\`\`bash
# Archive all WAL files in the archive directory
for wal in /path/to/archive/*; do
  dbdock wal:archive --file "$wal"
done
\`\`\`
`.trim();
  }
}
