jest.mock('ora', () => {
  return jest.fn(() => ({
    start: jest.fn().mockReturnThis(),
    succeed: jest.fn().mockReturnThis(),
    fail: jest.fn().mockReturnThis(),
    warn: jest.fn().mockReturnThis(),
    text: '',
  }));
});

jest.mock('chalk', () => ({
  bold: jest.fn((s) => s),
  gray: jest.fn((s) => s),
  green: jest.fn((s) => s),
  red: jest.fn((s) => s),
  blue: jest.fn((s) => s),
  yellow: jest.fn((s) => s),
}));

jest.mock('inquirer', () => ({
  prompt: jest.fn().mockResolvedValue({ confirm: true }),
}));

import {
  topologicalSort,
  generateColumnDDL,
  generateCreateTableDDL,
  generateForeignKeyDDL,
} from './driver-copy';

describe('driver-copy internals', () => {
  describe('generateColumnDDL', () => {
    it('should generate a basic text column', () => {
      const col = {
        name: 'email',
        type: 'text',
        nullable: true,
        defaultValue: null,
        identity: '',
        isGenerated: false,
      };
      expect(generateColumnDDL(col)).toBe('"email" text');
    });

    it('should generate a NOT NULL column', () => {
      const col = {
        name: 'name',
        type: 'character varying(255)',
        nullable: false,
        defaultValue: null,
        identity: '',
        isGenerated: false,
      };
      expect(generateColumnDDL(col)).toBe(
        '"name" character varying(255) NOT NULL',
      );
    });

    it('should generate a column with default', () => {
      const col = {
        name: 'active',
        type: 'boolean',
        nullable: false,
        defaultValue: 'true',
        identity: '',
        isGenerated: false,
      };
      expect(generateColumnDDL(col)).toBe(
        '"active" boolean DEFAULT true NOT NULL',
      );
    });

    it('should convert nextval integer to serial', () => {
      const col = {
        name: 'id',
        type: 'integer',
        nullable: false,
        defaultValue: "nextval('users_id_seq'::regclass)",
        identity: '',
        isGenerated: false,
      };
      expect(generateColumnDDL(col)).toBe('"id" serial');
    });

    it('should convert nextval bigint to bigserial', () => {
      const col = {
        name: 'id',
        type: 'bigint',
        nullable: false,
        defaultValue: "nextval('users_id_seq'::regclass)",
        identity: '',
        isGenerated: false,
      };
      expect(generateColumnDDL(col)).toBe('"id" bigserial');
    });

    it('should handle GENERATED ALWAYS AS IDENTITY', () => {
      const col = {
        name: 'id',
        type: 'integer',
        nullable: false,
        defaultValue: null,
        identity: 'a',
        isGenerated: false,
      };
      expect(generateColumnDDL(col)).toBe(
        '"id" integer GENERATED ALWAYS AS IDENTITY',
      );
    });

    it('should handle GENERATED BY DEFAULT AS IDENTITY', () => {
      const col = {
        name: 'id',
        type: 'bigint',
        nullable: false,
        defaultValue: null,
        identity: 'd',
        isGenerated: false,
      };
      expect(generateColumnDDL(col)).toBe(
        '"id" bigint GENERATED BY DEFAULT AS IDENTITY',
      );
    });

    it('should handle uuid column with gen_random_uuid default', () => {
      const col = {
        name: 'id',
        type: 'uuid',
        nullable: false,
        defaultValue: 'gen_random_uuid()',
        identity: '',
        isGenerated: false,
      };
      expect(generateColumnDDL(col)).toBe(
        '"id" uuid DEFAULT gen_random_uuid() NOT NULL',
      );
    });

    it('should handle timestamptz with now() default', () => {
      const col = {
        name: 'created_at',
        type: 'timestamp with time zone',
        nullable: false,
        defaultValue: 'now()',
        identity: '',
        isGenerated: false,
      };
      expect(generateColumnDDL(col)).toBe(
        '"created_at" timestamp with time zone DEFAULT now() NOT NULL',
      );
    });

    it('should handle nullable column with no default', () => {
      const col = {
        name: 'bio',
        type: 'text',
        nullable: true,
        defaultValue: null,
        identity: '',
        isGenerated: false,
      };
      expect(generateColumnDDL(col)).toBe('"bio" text');
    });

    it('should handle jsonb column', () => {
      const col = {
        name: 'metadata',
        type: 'jsonb',
        nullable: true,
        defaultValue: "'{}'::jsonb",
        identity: '',
        isGenerated: false,
      };
      expect(generateColumnDDL(col)).toBe(
        '"metadata" jsonb DEFAULT \'{}\'::jsonb',
      );
    });

    it('should handle array column', () => {
      const col = {
        name: 'tags',
        type: 'text[]',
        nullable: true,
        defaultValue: null,
        identity: '',
        isGenerated: false,
      };
      expect(generateColumnDDL(col)).toBe('"tags" text[]');
    });
  });

  describe('generateCreateTableDDL', () => {
    it('should generate DDL for a simple table', () => {
      const table = {
        name: 'users',
        columns: [
          {
            name: 'id',
            type: 'integer',
            nullable: false,
            defaultValue: "nextval('users_id_seq'::regclass)",
            identity: '',
            isGenerated: false,
          },
          {
            name: 'email',
            type: 'text',
            nullable: false,
            defaultValue: null,
            identity: '',
            isGenerated: false,
          },
          {
            name: 'name',
            type: 'character varying(255)',
            nullable: true,
            defaultValue: null,
            identity: '',
            isGenerated: false,
          },
        ],
        primaryKey: { constraintName: 'users_pkey', columns: ['id'] },
        uniqueConstraints: [
          { constraintName: 'users_email_key', columns: ['email'] },
        ],
        foreignKeys: [],
        indexes: [],
        rowCount: 100,
      };

      const ddl = generateCreateTableDDL(table);
      expect(ddl).toContain('CREATE TABLE "public"."users"');
      expect(ddl).toContain('"id" serial');
      expect(ddl).toContain('"email" text NOT NULL');
      expect(ddl).toContain('"name" character varying(255)');
      expect(ddl).toContain('CONSTRAINT "users_pkey" PRIMARY KEY ("id")');
      expect(ddl).toContain('CONSTRAINT "users_email_key" UNIQUE ("email")');
    });

    it('should exclude generated columns', () => {
      const table = {
        name: 'products',
        columns: [
          {
            name: 'id',
            type: 'integer',
            nullable: false,
            defaultValue: null,
            identity: 'd',
            isGenerated: false,
          },
          {
            name: 'price',
            type: 'numeric(10,2)',
            nullable: false,
            defaultValue: null,
            identity: '',
            isGenerated: false,
          },
          {
            name: 'total',
            type: 'numeric(10,2)',
            nullable: true,
            defaultValue: null,
            identity: '',
            isGenerated: true,
          },
        ],
        primaryKey: { constraintName: 'products_pkey', columns: ['id'] },
        uniqueConstraints: [],
        foreignKeys: [],
        indexes: [],
        rowCount: 0,
      };

      const ddl = generateCreateTableDDL(table);
      expect(ddl).not.toContain('"total"');
      expect(ddl).toContain('"price"');
    });

    it('should handle composite primary key', () => {
      const table = {
        name: 'tenant_users',
        columns: [
          {
            name: 'tenant_id',
            type: 'uuid',
            nullable: false,
            defaultValue: null,
            identity: '',
            isGenerated: false,
          },
          {
            name: 'user_id',
            type: 'uuid',
            nullable: false,
            defaultValue: null,
            identity: '',
            isGenerated: false,
          },
          {
            name: 'role',
            type: 'text',
            nullable: false,
            defaultValue: null,
            identity: '',
            isGenerated: false,
          },
        ],
        primaryKey: {
          constraintName: 'tenant_users_pkey',
          columns: ['tenant_id', 'user_id'],
        },
        uniqueConstraints: [],
        foreignKeys: [],
        indexes: [],
        rowCount: 0,
      };

      const ddl = generateCreateTableDDL(table);
      expect(ddl).toContain(
        'CONSTRAINT "tenant_users_pkey" PRIMARY KEY ("tenant_id", "user_id")',
      );
    });

    it('should handle table with no primary key', () => {
      const table = {
        name: 'logs',
        columns: [
          {
            name: 'message',
            type: 'text',
            nullable: false,
            defaultValue: null,
            identity: '',
            isGenerated: false,
          },
          {
            name: 'created_at',
            type: 'timestamp with time zone',
            nullable: false,
            defaultValue: 'now()',
            identity: '',
            isGenerated: false,
          },
        ],
        primaryKey: null,
        uniqueConstraints: [],
        foreignKeys: [],
        indexes: [],
        rowCount: 0,
      };

      const ddl = generateCreateTableDDL(table);
      expect(ddl).toContain('CREATE TABLE "public"."logs"');
      expect(ddl).not.toContain('PRIMARY KEY');
    });
  });

  describe('generateForeignKeyDDL', () => {
    it('should generate FK constraint DDL', () => {
      const table = {
        name: 'orders',
        columns: [],
        primaryKey: null,
        uniqueConstraints: [],
        foreignKeys: [
          {
            constraintName: 'orders_user_id_fkey',
            columns: ['user_id'],
            referencedTable: 'users',
            referencedColumns: ['id'],
            onDelete: 'CASCADE',
            onUpdate: 'NO ACTION',
          },
        ],
        indexes: [],
        rowCount: 0,
      };

      const ddls = generateForeignKeyDDL(table);
      expect(ddls).toHaveLength(1);
      expect(ddls[0]).toContain('ALTER TABLE "public"."orders"');
      expect(ddls[0]).toContain('ADD CONSTRAINT "orders_user_id_fkey"');
      expect(ddls[0]).toContain('FOREIGN KEY ("user_id")');
      expect(ddls[0]).toContain('REFERENCES "public"."users" ("id")');
      expect(ddls[0]).toContain('ON DELETE CASCADE');
      expect(ddls[0]).toContain('ON UPDATE NO ACTION');
    });

    it('should handle composite foreign keys', () => {
      const table = {
        name: 'order_items',
        columns: [],
        primaryKey: null,
        uniqueConstraints: [],
        foreignKeys: [
          {
            constraintName: 'order_items_fk',
            columns: ['tenant_id', 'order_id'],
            referencedTable: 'orders',
            referencedColumns: ['tenant_id', 'id'],
            onDelete: 'SET NULL',
            onUpdate: 'RESTRICT',
          },
        ],
        indexes: [],
        rowCount: 0,
      };

      const ddls = generateForeignKeyDDL(table);
      expect(ddls[0]).toContain('FOREIGN KEY ("tenant_id", "order_id")');
      expect(ddls[0]).toContain(
        'REFERENCES "public"."orders" ("tenant_id", "id")',
      );
      expect(ddls[0]).toContain('ON DELETE SET NULL');
      expect(ddls[0]).toContain('ON UPDATE RESTRICT');
    });

    it('should return empty array for no foreign keys', () => {
      const table = {
        name: 'settings',
        columns: [],
        primaryKey: null,
        uniqueConstraints: [],
        foreignKeys: [],
        indexes: [],
        rowCount: 0,
      };

      expect(generateForeignKeyDDL(table)).toEqual([]);
    });

    it('should handle multiple foreign keys', () => {
      const table = {
        name: 'payments',
        columns: [],
        primaryKey: null,
        uniqueConstraints: [],
        foreignKeys: [
          {
            constraintName: 'payments_user_id_fkey',
            columns: ['user_id'],
            referencedTable: 'users',
            referencedColumns: ['id'],
            onDelete: 'CASCADE',
            onUpdate: 'NO ACTION',
          },
          {
            constraintName: 'payments_order_id_fkey',
            columns: ['order_id'],
            referencedTable: 'orders',
            referencedColumns: ['id'],
            onDelete: 'SET NULL',
            onUpdate: 'NO ACTION',
          },
        ],
        indexes: [],
        rowCount: 0,
      };

      const ddls = generateForeignKeyDDL(table);
      expect(ddls).toHaveLength(2);
    });
  });

  describe('topologicalSort', () => {
    it('should sort tables by dependency order', () => {
      const tables = [
        {
          name: 'orders',
          columns: [],
          primaryKey: null,
          uniqueConstraints: [],
          foreignKeys: [
            {
              constraintName: 'fk_user',
              columns: ['user_id'],
              referencedTable: 'users',
              referencedColumns: ['id'],
              onDelete: 'CASCADE',
              onUpdate: 'NO ACTION',
            },
          ],
          indexes: [],
          rowCount: 0,
        },
        {
          name: 'users',
          columns: [],
          primaryKey: null,
          uniqueConstraints: [],
          foreignKeys: [],
          indexes: [],
          rowCount: 0,
        },
        {
          name: 'order_items',
          columns: [],
          primaryKey: null,
          uniqueConstraints: [],
          foreignKeys: [
            {
              constraintName: 'fk_order',
              columns: ['order_id'],
              referencedTable: 'orders',
              referencedColumns: ['id'],
              onDelete: 'CASCADE',
              onUpdate: 'NO ACTION',
            },
          ],
          indexes: [],
          rowCount: 0,
        },
      ];

      const sorted = topologicalSort(tables);
      const names = sorted.map((t: any) => t.name);

      expect(names.indexOf('users')).toBeLessThan(names.indexOf('orders'));
      expect(names.indexOf('orders')).toBeLessThan(
        names.indexOf('order_items'),
      );
    });

    it('should handle self-referencing tables', () => {
      const tables = [
        {
          name: 'categories',
          columns: [],
          primaryKey: null,
          uniqueConstraints: [],
          foreignKeys: [
            {
              constraintName: 'fk_parent',
              columns: ['parent_id'],
              referencedTable: 'categories',
              referencedColumns: ['id'],
              onDelete: 'SET NULL',
              onUpdate: 'NO ACTION',
            },
          ],
          indexes: [],
          rowCount: 0,
        },
      ];

      const sorted = topologicalSort(tables);
      expect(sorted).toHaveLength(1);
      expect(sorted[0].name).toBe('categories');
    });

    it('should handle circular dependencies without infinite loop', () => {
      const tables = [
        {
          name: 'a',
          columns: [],
          primaryKey: null,
          uniqueConstraints: [],
          foreignKeys: [
            {
              constraintName: 'fk_b',
              columns: ['b_id'],
              referencedTable: 'b',
              referencedColumns: ['id'],
              onDelete: 'NO ACTION',
              onUpdate: 'NO ACTION',
            },
          ],
          indexes: [],
          rowCount: 0,
        },
        {
          name: 'b',
          columns: [],
          primaryKey: null,
          uniqueConstraints: [],
          foreignKeys: [
            {
              constraintName: 'fk_a',
              columns: ['a_id'],
              referencedTable: 'a',
              referencedColumns: ['id'],
              onDelete: 'NO ACTION',
              onUpdate: 'NO ACTION',
            },
          ],
          indexes: [],
          rowCount: 0,
        },
      ];

      const sorted = topologicalSort(tables);
      expect(sorted).toHaveLength(2);
    });

    it('should handle tables with no dependencies', () => {
      const tables = [
        {
          name: 'logs',
          columns: [],
          primaryKey: null,
          uniqueConstraints: [],
          foreignKeys: [],
          indexes: [],
          rowCount: 0,
        },
        {
          name: 'settings',
          columns: [],
          primaryKey: null,
          uniqueConstraints: [],
          foreignKeys: [],
          indexes: [],
          rowCount: 0,
        },
      ];

      const sorted = topologicalSort(tables);
      expect(sorted).toHaveLength(2);
    });

    it('should handle deep dependency chains', () => {
      const tables = [
        {
          name: 'd',
          columns: [],
          primaryKey: null,
          uniqueConstraints: [],
          foreignKeys: [
            {
              constraintName: 'fk_c',
              columns: ['c_id'],
              referencedTable: 'c',
              referencedColumns: ['id'],
              onDelete: 'CASCADE',
              onUpdate: 'NO ACTION',
            },
          ],
          indexes: [],
          rowCount: 0,
        },
        {
          name: 'b',
          columns: [],
          primaryKey: null,
          uniqueConstraints: [],
          foreignKeys: [
            {
              constraintName: 'fk_a',
              columns: ['a_id'],
              referencedTable: 'a',
              referencedColumns: ['id'],
              onDelete: 'CASCADE',
              onUpdate: 'NO ACTION',
            },
          ],
          indexes: [],
          rowCount: 0,
        },
        {
          name: 'a',
          columns: [],
          primaryKey: null,
          uniqueConstraints: [],
          foreignKeys: [],
          indexes: [],
          rowCount: 0,
        },
        {
          name: 'c',
          columns: [],
          primaryKey: null,
          uniqueConstraints: [],
          foreignKeys: [
            {
              constraintName: 'fk_b',
              columns: ['b_id'],
              referencedTable: 'b',
              referencedColumns: ['id'],
              onDelete: 'CASCADE',
              onUpdate: 'NO ACTION',
            },
          ],
          indexes: [],
          rowCount: 0,
        },
      ];

      const sorted = topologicalSort(tables);
      const names = sorted.map((t: any) => t.name);

      expect(names.indexOf('a')).toBeLessThan(names.indexOf('b'));
      expect(names.indexOf('b')).toBeLessThan(names.indexOf('c'));
      expect(names.indexOf('c')).toBeLessThan(names.indexOf('d'));
    });
  });
});
