import { existsSync, readFileSync, writeFileSync, appendFileSync } from 'fs';
import { join } from 'path';
import { logger } from '../utils/logger';
import { Logger } from '@nestjs/common';
import { CONFIG_FILE } from '../utils/config';
import {
  hasSecretsInConfig,
  ENV_VAR_MAPPING,
  getNestedValue,
} from '../../config/secrets.validator';

Logger.overrideLogger(false);

const ENV_FILE = '.env';

interface SecretsMap {
  [key: string]: string;
}

export async function migrateConfigCommand(): Promise<void> {
  logger.info('🔐 DBDock Config Migration Tool');
  logger.info('');

  const configPath = join(process.cwd(), CONFIG_FILE);

  if (!existsSync(configPath)) {
    logger.error(`Configuration file not found: ${configPath}`);
    logger.log('Run "npx dbdock init" to create a new configuration.');
    process.exit(1);
  }

  const configContent = readFileSync(configPath, 'utf-8');
  const config = JSON.parse(configContent);

  const secretFields = hasSecretsInConfig(config);

  if (secretFields.length === 0) {
    logger.success('✓ No secrets found in configuration file.');
    logger.info('Your configuration is already secure!');
    return;
  }

  logger.warn(`Found ${secretFields.length} secret(s) in ${CONFIG_FILE}:`);
  secretFields.forEach((field) => {
    logger.log(`  • ${field}`);
  });
  logger.info('');

  const secrets = extractSecretsFromConfig(config, secretFields);

  const envPath = join(process.cwd(), ENV_FILE);
  const envExists = existsSync(envPath);

  if (envExists) {
    logger.info(`Updating existing ${ENV_FILE}...`);
    updateEnvFile(envPath, secrets);
  } else {
    logger.info(`Creating ${ENV_FILE}...`);
    createEnvFile(envPath, secrets);
  }

  logger.success(`✓ Secrets saved to ${ENV_FILE}`);

  const cleanedConfig = removeSecretsFromConfigData(config, secretFields);

  const backupPath = `${configPath}.backup`;
  writeFileSync(backupPath, configContent);
  logger.success(`✓ Original config backed up to ${CONFIG_FILE}.backup`);

  writeFileSync(configPath, JSON.stringify(cleanedConfig, null, 2) + '\n');
  logger.success(`✓ Secrets removed from ${CONFIG_FILE}`);

  updateGitignore();

  logger.info('');
  logger.success('🎉 Migration completed successfully!');
  logger.info('');
  logger.info('Next steps:');
  logger.log(`  1. Review ${ENV_FILE} to ensure all secrets are correct`);
  logger.log('  2. Ensure .env is in your .gitignore');
  logger.log('  3. Run "npx dbdock test" to verify your configuration');
  logger.log(
    "  4. Delete the backup file when you're confident: rm dbdock.config.json.backup",
  );
  logger.info('');
  logger.warn('⚠️  IMPORTANT: Do NOT commit .env to version control!');
}

function extractSecretsFromConfig(
  config: Record<string, unknown>,
  secretFields: string[],
): SecretsMap {
  const secrets: SecretsMap = {};

  for (const field of secretFields) {
    const value = getNestedValue(config, field);
    const envVar = ENV_VAR_MAPPING[field];

    if (value && typeof value === 'string' && envVar) {
      secrets[envVar] = value;
    }
  }

  return secrets;
}

function removeSecretsFromConfigData(
  config: Record<string, unknown>,
  secretFields: string[],
): Record<string, unknown> {
  const cleaned = JSON.parse(JSON.stringify(config));

  for (const field of secretFields) {
    const parts = field.split('.');
    let current = cleaned;

    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i];
      if (current[part] && typeof current[part] === 'object') {
        current = current[part] as Record<string, unknown>;
      } else {
        break;
      }
    }

    const lastPart = parts[parts.length - 1];
    if (current && typeof current === 'object' && lastPart in current) {
      delete current[lastPart];
    }
  }

  return cleaned;
}

function createEnvFile(path: string, secrets: SecretsMap): void {
  const lines = [
    '# DBDock Secrets - DO NOT COMMIT THIS FILE',
    '# Generated by dbdock migrate-config',
    '',
  ];

  for (const [key, value] of Object.entries(secrets)) {
    lines.push(`${key}=${value}`);
  }

  lines.push('');

  writeFileSync(path, lines.join('\n'), { mode: 0o600 });
}

function updateEnvFile(path: string, secrets: SecretsMap): void {
  const content = readFileSync(path, 'utf-8');
  const lines = content.split('\n');

  const existingKeys = new Set<string>();
  const updatedLines: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key] = trimmed.split('=');
      if (key) {
        existingKeys.add(key.trim());

        if (secrets[key.trim()]) {
          updatedLines.push(`${key.trim()}=${secrets[key.trim()]}`);
        } else {
          updatedLines.push(line);
        }
      } else {
        updatedLines.push(line);
      }
    } else {
      updatedLines.push(line);
    }
  }

  for (const [key, value] of Object.entries(secrets)) {
    if (!existingKeys.has(key)) {
      updatedLines.push(`${key}=${value}`);
    }
  }

  if (!updatedLines[updatedLines.length - 1]?.trim()) {
    updatedLines.push('');
  }

  writeFileSync(path, updatedLines.join('\n'), { mode: 0o600 });
}

function updateGitignore(): void {
  const gitignorePath = join(process.cwd(), '.gitignore');

  if (!existsSync(gitignorePath)) {
    writeFileSync(gitignorePath, `${ENV_FILE}\n`);
    logger.success('✓ Created .gitignore with .env');
    return;
  }

  const content = readFileSync(gitignorePath, 'utf-8');
  const lines = content.split('\n');

  const hasEnv = lines.some((line) =>
    ['.env', '/.env', './.env'].includes(line.trim()),
  );

  if (!hasEnv) {
    const needsNewline = content.length > 0 && !content.endsWith('\n');
    const contentToAdd = needsNewline ? `\n${ENV_FILE}\n` : `${ENV_FILE}\n`;

    appendFileSync(gitignorePath, contentToAdd);
    logger.success(`✓ Added ${ENV_FILE} to .gitignore`);
  } else {
    logger.info('✓ .env already in .gitignore');
  }
}
